//! OpenSlope API Key Generation Module
//!
//! This module provides cryptographically secure API key generation functionality
//! for the OpenSlope API. API keys are used for authenticating requests to protected
//! endpoints and ensuring only authorized users can access sensitive data.
//!
//! # Security Features
//!
//! - **Cryptographically Secure Random Generation**: Uses the operating system's
//!   cryptographically secure random number generator (CSPRNG)
//! - **32-byte Key Length**: Provides 256 bits of entropy for maximum security
//! - **URL-Safe Base64 Encoding**: Ensures API keys can be safely transmitted
//!   in URLs and HTTP headers without encoding issues
//! - **No Padding**: Uses URL-safe base64 encoding without padding characters
//!
//! # Key Generation Process
//!
//! 1. **Entropy Source**: Uses `OsRng` (Operating System Random Number Generator)
//!    which provides cryptographically secure random bytes
//! 2. **Key Length**: Generates 32 bytes (256 bits) of random data
//! 3. **Encoding**: Encodes the random bytes using URL-safe base64 without padding
//! 4. **Output**: Returns a string that can be safely used in URLs and headers
//!
//! # Security Considerations
//!
//! - **Entropy**: 256 bits of entropy makes brute force attacks computationally infeasible
//! - **Unpredictability**: Uses cryptographically secure random generation
//! - **Transmission Safety**: URL-safe encoding prevents issues with special characters
//! - **Storage**: API keys should be stored hashed in the database (see hash module)
//!
//! # Usage Examples
//!
//! ```rust
//! use openslope_api::security::api_key;
//!
//! // Generate a new API key
//! let api_key = api_key::generate_api_key();
//! println!("Generated API Key: {}", api_key);
//!
//! // Example output: "4f7a9c2e8b1d5f3a7c9e2d4f8a6b3c5e7d9f1a2b4c6d8e0f3a5b7c9d1e3f5a7"
//! ```
//!
//! # API Key Format
//!
//! Generated API keys follow this format:
//! - **Length**: 43 characters (due to base64 encoding of 32 bytes)
//! - **Characters**: URL-safe base64 characters (A-Z, a-z, 0-9, -, _)
//! - **No Padding**: No '=' characters at the end
//!
//! # Integration with Authentication
//!
//! API keys generated by this module are used in conjunction with the authentication
//! system:
//! 1. Keys are generated during user registration or login
//! 2. Keys are hashed before storing in the database
//! 3. Keys are verified against stored hashes during authentication
//! 4. Keys are passed via query parameters in API requests
//!
//! # Security Best Practices
//!
//! - **HTTPS Required**: Always use HTTPS in production to protect API keys in transit
//! - **Key Rotation**: Consider implementing periodic key rotation
//! - **Access Control**: Limit API key usage to specific IP ranges if possible
//! - **Monitoring**: Log API key usage for security monitoring
//! - **Expiration**: Consider implementing key expiration for enhanced security
//!
//! # Performance Characteristics
//!
//! - **Generation Speed**: Very fast - single function call
//! - **Memory Usage**: Minimal - only 32 bytes of random data
//! - **Encoding Overhead**: Minimal - base64 encoding adds ~33% size overhead
//!
//! Author: OpenSlope Team
//! Version: 1.0.0

use rand::RngCore;
use rand::rngs::OsRng;
use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine};

/// Generate a cryptographically secure API key
///
/// This function creates a 32-byte (256-bit) cryptographically secure random key
/// and encodes it using URL-safe base64 encoding without padding.
///
/// # Returns
///
/// A string containing the generated API key, 43 characters long, using only
/// URL-safe characters (A-Z, a-z, 0-9, -, _).
///
/// # Security Properties
///
/// - **Entropy**: 256 bits of cryptographically secure randomness
/// - **Unpredictability**: Uses operating system CSPRNG
/// - **URL Safety**: Safe for use in URLs and HTTP headers
/// - **Collision Resistance**: Extremely low probability of key collisions
///
/// # Example
///
/// ```rust
/// let api_key = generate_api_key();
/// assert_eq!(api_key.len(), 43);
/// assert!(api_key.chars().all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_'));
/// ```
///
/// # Implementation Details
///
/// 1. Creates a 32-byte array for random data
/// 2. Fills the array with cryptographically secure random bytes using OsRng
/// 3. Encodes the bytes using URL-safe base64 without padding
/// 4. Returns the encoded string
pub fn generate_api_key() -> String {
    let mut bytes = [0u8; 32];

    let mut rng = OsRng;
    rng.fill_bytes(&mut bytes);

    URL_SAFE_NO_PAD.encode(bytes)
}
