"""
Unified OSM Data Collection Worker for Openslope

This script fetches ski slopes and lifts from OpenStreetMap via the Overpass API
and syncs them to the Openslope REST API. It is designed to run as a single worker
instance within a parallel processing system managed by launcher.py.

## Key Features

- **Parallelizable**: Each worker processes a specific longitude range
- **Idempotent**: Uses OSM ID as unique identifier; upserts (insert or update)
- **Resumable**: Saves progress to JSON file; resumes from last processed OSM ID
- **Fault-tolerant**: Skips bad records without crashing; logs errors
- **Dry-run mode**: Preview API calls without executing them

## Database Schema Mapping

Based on analysis of the Openslope API server code (server/src/routes/):

### Slopes Table Columns:
- id (i64, auto-generated by API)
- resort_id (String, required) - Set to NULL placeholder "unassigned" since resort assignment is done later
- name (Option<String>)
- difficulty (String, required) - Mapped from piste:difficulty, defaults to "unknown"
- name_normalized (Option<String>)
- length_m, vertical_drop_m, average_gradient, max_gradient (optional numeric specs)
- snowmaking, night_skiing, family_friendly, race_slope (boolean flags)
- lat_start, lon_start, lat_end, lon_end (Option<f64>)
- path_geojson (Option<String>) - Complete geometry as GeoJSON
- direction (Option<f64>)
- source_system (String) - Always "osm" for this script
- source_entity_id (Option<String>) - Stores the OSM ID (e.g., "way/12345")
- operational_status (String) - Defaults to "unknown"
- grooming_status (String) - Mapped from piste:grooming, defaults to "unknown"
- operational_note, status_updated_at, status_source_url (optional status fields)

### Lifts Table Columns:
- id (i64, auto-generated by API)
- resort_id (String, required) - Set to NULL placeholder "unassigned" since resort assignment is done later
- name (Option<String>)
- lift_type (String, required) - Mapped from aerialway tag, defaults to "unknown"
- name_normalized (Option<String>)
- capacity_per_hour, seats, year_built (optional specs)
- bubble, heated_seats (boolean flags)
- altitude_start_m, altitude_end_m (optional altitude data)
- lat_start, lon_start, lat_end, lon_end (Option<f64>)
- source_system (String) - Always "osm" for this script
- source_entity_id (Option<String>) - Stores the OSM ID (e.g., "way/12345")
- operational_status (String) - Defaults to "unknown"
- operational_note, planned_open_time, planned_close_time, status_updated_at, status_source_url (optional)

## Usage

### Single worker with longitude range:
    python collect_and_sync.py --instance-id 1 --lng-min -180 --lng-max -144

### Dry-run mode (preview without executing):
    python collect_and_sync.py --instance-id 1 --lng-min -180 --lng-max -144 --dry-run

### Clear progress files:
    python collect_and_sync.py --clear

## Author
Openslope Team

## Version
1.0.0
"""

import argparse
import json
import logging
import math
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

import requests
from urllib3.util.retry import Retry
from requests.adapters import HTTPAdapter

# Import shared configuration
from config import (
    API_BASE_URL,
    API_KEY,
    BATCH_SIZE,
    DEFAULT_INSTANCES,
    HEADERS,
    HTTP_RETRIES,
    LOG_LEVEL,
    OVERPASS_TIMEOUT,
    OVERPASS_URL,
    PROGRESS_DIR,
    REQUEST_DELAY,
    SLOPES_ENDPOINT,
    LIFTS_ENDPOINT,
)

# =============================================================================
# Logger Setup
# =============================================================================


def setup_logger() -> logging.Logger:
    """Configure and return the application logger."""
    logger = logging.getLogger("collect_and_sync")
    logger.setLevel(getattr(logging, LOG_LEVEL.upper(), logging.INFO))

    formatter = logging.Formatter(
        fmt="%(asctime)s  [%(levelname)-8s]  %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    console_handler = logging.StreamHandler()
    console_handler.setFormatter(formatter)
    logger.addHandler(console_handler)

    return logger


log = setup_logger()


# =============================================================================
# HTTP Session with Retry Logic
# =============================================================================


def create_session() -> requests.Session:
    """Create a requests session with exponential backoff retry strategy."""
    session = requests.Session()
    retry_strategy = Retry(
        total=HTTP_RETRIES,
        backoff_factor=2,
        status_forcelist=[429, 500, 502, 503, 504, 408],
        allowed_methods=["HEAD", "GET", "OPTIONS", "POST", "PUT", "DELETE"],
    )
    adapter = HTTPAdapter(max_retries=retry_strategy)
    session.mount("http://", adapter)
    session.mount("https://", adapter)
    return session


SESSION = create_session()


# =============================================================================
# Progress Tracking
# =============================================================================


def get_progress_file(instance_id: int) -> Path:
    """Return the path to the progress file for this worker instance."""
    return Path(PROGRESS_DIR) / f"progress_{instance_id}.json"


def load_progress(instance_id: int) -> dict:
    """Load progress state from file, or return default state."""
    progress_file = get_progress_file(instance_id)
    if progress_file.exists():
        try:
            with open(progress_file, "r") as f:
                return json.load(f)
        except (json.JSONDecodeError, IOError) as e:
            log.warning("Failed to load progress file: %s", e)
    return {
        "instance_id": instance_id,
        "lng_min": None,
        "lng_max": None,
        "last_processed_osm_id": None,
        "last_run_timestamp": None,
        "slopes_synced": 0,
        "lifts_synced": 0,
        "slopes_updated": 0,
        "lifts_updated": 0,
        "skipped": [],
    }


def save_progress(instance_id: int, progress: dict) -> None:
    """Save progress state to file."""
    progress_file = get_progress_file(instance_id)
    progress["last_run_timestamp"] = datetime.now(timezone.utc).isoformat()
    with open(progress_file, "w") as f:
        json.dump(progress, f, indent=2)


def clear_all_progress() -> None:
    """Clear all progress files."""
    progress_dir = Path(PROGRESS_DIR)
    for f in progress_dir.glob("progress_*.json"):
        f.unlink()
        log.info("Cleared progress file: %s", f.name)


# =============================================================================
# Overpass API Queries
# =============================================================================


def query_osm_slopes(bbox: dict) -> list[dict]:
    """
    Query Overpass API for all ski slopes (piste:type=*) within a bounding box.
    
    Returns a list of OSM elements with their tags and geometry.
    """
    query = f"""
    [out:json][timeout:{OVERPASS_TIMEOUT}];
    (
      way["piste:type"]({bbox['min_lat']},{bbox['min_lon']},{bbox['max_lat']},{bbox['max_lon']});
      relation["piste:type"]({bbox['min_lat']},{bbox['min_lon']},{bbox['max_lat']},{bbox['max_lon']});
    );
    out body;
    >;
    out skel qt;
    """
    try:
        time.sleep(REQUEST_DELAY)
        response = SESSION.post(OVERPASS_URL, data={"data": query}, timeout=OVERPASS_TIMEOUT + 30)
        response.raise_for_status()
        return response.json().get("elements", [])
    except requests.RequestException as e:
        log.error("Overpass query failed for slopes: %s", e)
        return []


def query_osm_lifts(bbox: dict) -> list[dict]:
    """
    Query Overpass API for all aerialways (lifts) within a bounding box.
    
    Returns a list of OSM elements with their tags and geometry.
    """
    query = f"""
    [out:json][timeout:{OVERPASS_TIMEOUT}];
    (
      way["aerialway"]({bbox['min_lat']},{bbox['min_lon']},{bbox['max_lat']},{bbox['max_lon']});
      relation["aerialway"]({bbox['min_lat']},{bbox['min_lon']},{bbox['max_lat']},{bbox['max_lon']});
    );
    out body;
    >;
    out skel qt;
    """
    try:
        time.sleep(REQUEST_DELAY)
        response = SESSION.post(OVERPASS_URL, data={"data": query}, timeout=OVERPASS_TIMEOUT + 30)
        response.raise_for_status()
        return response.json().get("elements", [])
    except requests.RequestException as e:
        log.error("Overpass query failed for lifts: %s", e)
        return []


# =============================================================================
# OSM Data Parsing
# =============================================================================


def build_node_map(elements: list[dict]) -> dict[int, tuple[float, float]]:
    """Build a map of node ID -> (lon, lat) from OSM elements."""
    node_map = {}
    for el in elements:
        if el.get("type") == "node":
            node_map[el["id"]] = (el["lon"], el["lat"])
    return node_map


def extract_geometry(element: dict, node_map: dict) -> tuple[list, Optional[float], Optional[float]]:
    """
    Extract geometry from an OSM way or relation.
    
    Returns:
        - List of [lon, lat] coordinate pairs
        - Direction (azimuth in degrees) if calculable
        - None values if geometry cannot be extracted
    """
    coords = []
    
    if element.get("type") == "way":
        for node_id in element.get("nodes", []):
            if node_id in node_map:
                coords.append(list(node_map[node_id]))
    
    elif element.get("type") == "relation":
        # For relations, collect all member way nodes
        member_nodes = []
        for member in element.get("members", []):
            if member.get("type") == "way" and member.get("ref") in node_map:
                member_nodes.append(node_map[member["ref"]])
        if member_nodes:
            coords = [list(n) for n in member_nodes]
    
    # Calculate direction (azimuth) from first and last points
    direction = None
    if len(coords) >= 2:
        lon1, lat1 = coords[0]
        lon2, lat2 = coords[-1]
        # Calculate bearing from start to end
        d_lon = math.radians(lon2 - lon1)
        lat1_rad = math.radians(lat1)
        lat2_rad = math.radians(lat2)
        x = math.sin(d_lon) * math.cos(lat2_rad)
        y = math.cos(lat1_rad) * math.sin(lat2_rad) - \
            math.sin(lat1_rad) * math.cos(lat2_rad) * math.cos(d_lon)
        bearing = math.atan2(x, y)
        direction = (math.degrees(bearing) + 360) % 360
    
    return coords, direction


def parse_osm_slope(element: dict, node_map: dict) -> Optional[dict]:
    """
    Parse an OSM slope element into a structured dict matching the API schema.
    
    Returns None if the element cannot be parsed.
    """
    tags = element.get("tags", {})
    
    # Skip if not a piste
    if "piste:type" not in tags:
        return None
    
    # Generate OSM ID string (e.g., "way/12345" or "relation/67890")
    osm_type = element.get("type", "unknown")
    osm_id = element.get("id")
    if osm_id is None:
        return None
    source_entity_id = f"{osm_type}/{osm_id}"
    
    # Extract geometry
    coords, direction = extract_geometry(element, node_map)
    
    # Get start/end coordinates
    lat_start = coords[0][1] if coords else None
    lon_start = coords[0][0] if coords else None
    lat_end = coords[-1][1] if coords else None
    lon_end = coords[-1][0] if coords else None
    
    # Map piste:difficulty to API difficulty values
    # OSM uses: novice, easy, intermediate, advanced, expert, freeride
    # API uses: green, blue, red, black, unknown
    osm_difficulty = tags.get("piste:difficulty", "unknown").lower().strip()
    difficulty_map = {
        "novice": "green",
        "easy": "green",
        "intermediate": "blue",
        "advanced": "red",
        "expert": "black",
        "freeride": "black",
        "extreme": "black",
    }
    difficulty = difficulty_map.get(osm_difficulty, "unknown")
    
    # Map piste:grooming to API grooming_status
    grooming = tags.get("piste:grooming", "").lower().strip()
    if grooming in ("yes", "daily", "frequently"):
        grooming_status = "groomed"
    elif grooming == "no":
        grooming_status = "ungroomed"
    elif grooming == "occasional":
        grooming_status = "partially groomed"
    else:
        grooming_status = "unknown"
    
    # Build path GeoJSON string
    path_geojson = None
    if coords:
        path_points = [{"latitude": c[1], "longitude": c[0]} for c in coords]
        path_geojson = json.dumps(path_points)
    
    # Normalize name (lowercase, stripped)
    name = tags.get("name", "").strip()
    name_normalized = name.lower().strip() if name else None
    
    return {
        # Required fields
        "resort_id": "unassigned",  # Placeholder: resort assignment done later
        "name": name if name else None,
        "difficulty": difficulty,
        
        # Optional fields from OSM tags
        "name_normalized": name_normalized,
        "length_m": None,  # Not available from OSM directly
        "vertical_drop_m": None,
        "average_gradient": None,
        "max_gradient": None,
        
        # Boolean flags - check for oneway, lit tags
        "snowmaking": False,  # Not directly available from OSM piste tags
        "night_skiing": tags.get("lit", "").lower() in ("yes", "true"),
        "family_friendly": False,  # Not directly available
        "race_slope": tags.get("piste:type") == "racing",  # Racing pistes
        
        # Geometry
        "lat_start": lat_start,
        "lon_start": lon_start,
        "lat_end": lat_end,
        "lon_end": lon_end,
        "slope_path_json": path_geojson,
        "direction": direction,
        
        # Source tracking
        "source_system": "osm",
        "source_entity_id": source_entity_id,
        
        # Status fields
        "operational_status": "unknown",
        "grooming_status": grooming_status,
        "operational_note": None,
        "status_updated_at": None,
        "status_source_url": None,
        
        # Metadata for tracking
        "_osm_type": osm_type,
        "_osm_id": osm_id,
    }


def parse_osm_lift(element: dict, node_map: dict) -> Optional[dict]:
    """
    Parse an OSM lift element into a structured dict matching the API schema.
    
    Returns None if the element cannot be parsed.
    """
    tags = element.get("tags", {})
    
    # Skip if not an aerialway
    if "aerialway" not in tags:
        return None
    
    # Generate OSM ID string
    osm_type = element.get("type", "unknown")
    osm_id = element.get("id")
    if osm_id is None:
        return None
    source_entity_id = f"{osm_type}/{osm_id}"
    
    # Extract geometry
    coords, _ = extract_geometry(element, node_map)
    
    # Get start/end coordinates
    lat_start = coords[0][1] if coords else None
    lon_start = coords[0][0] if coords else None
    lat_end = coords[-1][1] if coords else None
    lon_end = coords[-1][0] if coords else None
    
    # Map aerialway type to API lift_type
    # OSM uses: chair_lift, gondola, drag_lift, goodold_tow, magic_carpet, etc.
    # API uses: chairlift, gondola, draglift, t-bar, magic_carpet, cable_car, etc.
    aerialway = tags.get("aerialway", "unknown").lower().strip()
    lift_type_map = {
        "chair_lift": "chairlift",
        "gondola": "gondola",
        "drag_lift": "draglift",
        "goodold_tow": "draglift",
        "t-bar": "draglift",
        "magic_carpet": "magic_carpet",
        "cable_car": "cable_car",
        "funitel": "funitel",
        "mixed_lift": "mixed",
        "zip_line": "zip_line",
        "rope_tow": "draglift",
        "platter": "draglift",
        "button_lift": "draglift",
    }
    lift_type = lift_type_map.get(aerialway, aerialway)
    
    # Normalize name
    name = tags.get("name", "").strip()
    name_normalized = name.lower().strip() if name else None
    
    # Parse capacity if available
    capacity_per_hour = None
    try:
        capacity_str = tags.get("capacity:hourly", tags.get("capacity", ""))
        if capacity_str:
            capacity_per_hour = int(capacity_str)
    except (ValueError, TypeError):
        pass
    
    # Parse seats/occupancy
    seats = None
    try:
        seats_str = tags.get("seats", tags.get("occupancy", ""))
        if seats_str:
            seats = int(seats_str)
    except (ValueError, TypeError):
        pass
    
    # Check for bubble/heated seats
    bubble = tags.get("bubble", "").lower() in ("yes", "true", "1")
    heated_seats = tags.get("heated_seats", "").lower() in ("yes", "true", "1")
    
    return {
        # Required fields
        "resort_id": "unassigned",  # Placeholder: resort assignment done later
        "name": name if name else None,
        "lift_type": lift_type,
        
        # Optional fields
        "name_normalized": name_normalized,
        "capacity_per_hour": capacity_per_hour,
        "seats": seats,
        "bubble": bubble,
        "heated_seats": heated_seats,
        "year_built": None,  # Not available from OSM
        "altitude_start_m": None,  # Could be derived from elevation tags
        "altitude_end_m": None,
        
        # Geometry
        "lat_start": lat_start,
        "lon_start": lon_start,
        "lat_end": lat_end,
        "lon_end": lon_end,
        
        # Source tracking
        "source_system": "osm",
        "source_entity_id": source_entity_id,
        
        # Status fields
        "operational_status": "unknown",
        "operational_note": None,
        "planned_open_time": None,
        "planned_close_time": None,
        "status_updated_at": None,
        "status_source_url": None,
        
        # Metadata for tracking
        "_osm_type": osm_type,
        "_osm_id": osm_id,
    }


# =============================================================================
# API Interaction
# =============================================================================


def check_slope_exists(source_entity_id: str) -> Optional[int]:
    """
    Check if a slope with the given OSM source_entity_id already exists.
    
    Returns the API slope ID if found, None otherwise.
    """
    try:
        time.sleep(REQUEST_DELAY)
        response = SESSION.get(SLOPES_ENDPOINT, headers=HEADERS, timeout=60)
        if response.status_code != 200:
            log.error("Failed to fetch slopes for existence check: %d", response.status_code)
            return None
        
        for slope in response.json():
            if slope.get("source", {}).get("entity_id") == source_entity_id:
                return slope["id"]
    except requests.RequestException as e:
        log.error("Error checking slope existence: %s", e)
    return None


def check_lift_exists(source_entity_id: str) -> Optional[int]:
    """
    Check if a lift with the given OSM source_entity_id already exists.
    
    Returns the API lift ID if found, None otherwise.
    """
    try:
        time.sleep(REQUEST_DELAY)
        response = SESSION.get(LIFTS_ENDPOINT, headers=HEADERS, timeout=60)
        if response.status_code != 200:
            log.error("Failed to fetch lifts for existence check: %d", response.status_code)
            return None
        
        for lift in response.json():
            if lift.get("source", {}).get("entity_id") == source_entity_id:
                return lift["id"]
    except requests.RequestException as e:
        log.error("Error checking lift existence: %s", e)
    return None


def create_or_update_slope(slope_data: dict, dry_run: bool = False) -> tuple[bool, str]:
    """
    Create a new slope or update an existing one via the API.
    
    Returns (success, message) tuple.
    """
    # Check if already exists
    existing_id = None
    if not dry_run:
        existing_id = check_slope_exists(slope_data["source_entity_id"])
    
    if existing_id:
        # Update existing slope
        if dry_run:
            return True, f"DRY RUN: Would update slope (existing_id={existing_id})"
        
        try:
            time.sleep(REQUEST_DELAY)
            url = f"{SLOPES_ENDPOINT}/{existing_id}"
            response = SESSION.put(url, json=slope_data, headers=HEADERS, timeout=30)
            if response.status_code == 200:
                return True, f"Updated slope {existing_id}"
            else:
                return False, f"Update failed: {response.status_code} - {response.text}"
        except requests.RequestException as e:
            return False, f"Update error: {e}"
    else:
        # Create new slope
        if dry_run:
            return True, "DRY RUN: Would create new slope"
        
        try:
            time.sleep(REQUEST_DELAY)
            response = SESSION.post(SLOPES_ENDPOINT, json=slope_data, headers=HEADERS, timeout=30)
            if response.status_code == 201:
                return True, f"Created slope (id={response.json()})"
            else:
                return False, f"Create failed: {response.status_code} - {response.text}"
        except requests.RequestException as e:
            return False, f"Create error: {e}"


def create_or_update_lift(lift_data: dict, dry_run: bool = False) -> tuple[bool, str]:
    """
    Create a new lift or update an existing one via the API.
    
    Returns (success, message) tuple.
    """
    # Check if already exists
    existing_id = None
    if not dry_run:
        existing_id = check_lift_exists(lift_data["source_entity_id"])
    
    if existing_id:
        # Update existing lift
        if dry_run:
            return True, f"DRY RUN: Would update lift (existing_id={existing_id})"
        
        try:
            time.sleep(REQUEST_DELAY)
            url = f"{LIFTS_ENDPOINT}/{existing_id}"
            response = SESSION.put(url, json=lift_data, headers=HEADERS, timeout=30)
            if response.status_code == 200:
                return True, f"Updated lift {existing_id}"
            else:
                return False, f"Update failed: {response.status_code} - {response.text}"
        except requests.RequestException as e:
            return False, f"Update error: {e}"
    else:
        # Create new lift
        if dry_run:
            return True, "DRY RUN: Would create new lift"
        
        try:
            time.sleep(REQUEST_DELAY)
            response = SESSION.post(LIFTS_ENDPOINT, json=lift_data, headers=HEADERS, timeout=30)
            if response.status_code == 201:
                return True, f"Created lift (id={response.json()})"
            else:
                return False, f"Create failed: {response.status_code} - {response.text}"
        except requests.RequestException as e:
            return False, f"Create error: {e}"


# =============================================================================
# Main Processing Logic
# =============================================================================


def process_slopes(elements: list[dict], progress: dict, dry_run: bool, instance_id: int) -> dict:
    """Process a batch of OSM slope elements and sync to API."""
    node_map = build_node_map(elements)
    
    slopes_created = 0
    slopes_updated = 0
    slopes_skipped = 0
    
    for element in elements:
        if element.get("type") not in ("way", "relation"):
            continue
        
        try:
            slope_data = parse_osm_slope(element, node_map)
            if slope_data is None:
                continue
            
            # Check if we should skip (already processed)
            osm_id = f"{slope_data['_osm_type']}/{slope_data['_osm_id']}"
            if progress.get("last_processed_osm_id") == osm_id:
                log.debug("Skipping already processed: %s", osm_id)
                continue
            
            # Clean internal metadata before sending to API
            api_data = {k: v for k, v in slope_data.items() if not k.startswith("_")}
            
            success, message = create_or_update_slope(api_data, dry_run)
            
            if success:
                if "update" in message.lower():
                    slopes_updated += 1
                else:
                    slopes_created += 1
                progress["last_processed_osm_id"] = osm_id
            else:
                slopes_skipped += 1
                progress["skipped"].append({"osm_id": osm_id, "reason": message})
                log.warning("Skipped slope %s: %s", osm_id, message)
                
        except Exception as e:
            slopes_skipped += 1
            osm_id = f"{element.get('type', 'unknown')}/{element.get('id', 'unknown')}"
            progress["skipped"].append({"osm_id": osm_id, "reason": str(e)})
            log.error("Error processing slope %s: %s", osm_id, e)
    
    return {
        "created": slopes_created,
        "updated": slopes_updated,
        "skipped": slopes_skipped,
    }


def process_lifts(elements: list[dict], progress: dict, dry_run: bool, instance_id: int) -> dict:
    """Process a batch of OSM lift elements and sync to API."""
    node_map = build_node_map(elements)
    
    lifts_created = 0
    lifts_updated = 0
    lifts_skipped = 0
    
    for element in elements:
        if element.get("type") not in ("way", "relation"):
            continue
        
        try:
            lift_data = parse_osm_lift(element, node_map)
            if lift_data is None:
                continue
            
            # Check if we should skip (already processed)
            osm_id = f"{lift_data['_osm_type']}/{lift_data['_osm_id']}"
            if progress.get("last_processed_osm_id") == osm_id:
                log.debug("Skipping already processed: %s", osm_id)
                continue
            
            # Clean internal metadata before sending to API
            api_data = {k: v for k, v in lift_data.items() if not k.startswith("_")}
            
            success, message = create_or_update_lift(api_data, dry_run)
            
            if success:
                if "update" in message.lower():
                    lifts_updated += 1
                else:
                    lifts_created += 1
                progress["last_processed_osm_id"] = osm_id
            else:
                lifts_skipped += 1
                progress["skipped"].append({"osm_id": osm_id, "reason": message})
                log.warning("Skipped lift %s: %s", osm_id, message)
                
        except Exception as e:
            lifts_skipped += 1
            osm_id = f"{element.get('type', 'unknown')}/{element.get('id', 'unknown')}"
            progress["skipped"].append({"osm_id": osm_id, "reason": str(e)})
            log.error("Error processing lift %s: %s", osm_id, e)
    
    return {
        "created": lifts_created,
        "updated": lifts_updated,
        "skipped": lifts_skipped,
    }


def run_worker(instance_id: int, lng_min: float, lng_max: float, dry_run: bool) -> None:
    """
    Main worker function that processes a longitude range.
    
    The worker queries OSM for the full latitude range (-90 to +90) within
    the assigned longitude band, processes slopes and lifts in batches,
    and syncs them to the API.
    """
    log.info("=" * 60)
    log.info("Starting worker %d: longitude %.2f to %.2f", instance_id, lng_min, lng_max)
    if dry_run:
        log.info("*** DRY RUN MODE - No changes will be made ***")
    log.info("=" * 60)
    
    # Load or initialize progress
    progress = load_progress(instance_id)
    progress["lng_min"] = lng_min
    progress["lng_max"] = lng_max
    
    # Define bounding box for this worker (full latitude range)
    bbox = {
        "min_lat": -90.0,
        "max_lat": 90.0,
        "min_lon": lng_min,
        "max_lon": lng_max,
    }
    
    # Query slopes from OSM
    log.info("Querying OSM for slopes in longitude range [%.2f, %.2f]...", lng_min, lng_max)
    slope_elements = query_osm_slopes(bbox)
    log.info("Found %d slope elements from OSM", len(slope_elements))
    
    # Process slopes in batches
    if slope_elements:
        total_slopes = len(slope_elements)
        for i in range(0, total_slopes, BATCH_SIZE):
            batch = slope_elements[i:i + BATCH_SIZE]
            log.info("Processing slope batch %d-%d of %d", i + 1, min(i + BATCH_SIZE, total_slopes), total_slopes)
            
            result = process_slopes(batch, progress, dry_run, instance_id)
            progress["slopes_synced"] = progress.get("slopes_synced", 0) + result["created"]
            progress["slopes_updated"] = progress.get("slopes_updated", 0) + result["updated"]
            
            log.info("  Batch result: %d created, %d updated, %d skipped",
                     result["created"], result["updated"], result["skipped"])
            
            # Save progress after each batch
            save_progress(instance_id, progress)
    
    # Query lifts from OSM
    log.info("Querying OSM for lifts in longitude range [%.2f, %.2f]...", lng_min, lng_max)
    lift_elements = query_osm_lifts(bbox)
    log.info("Found %d lift elements from OSM", len(lift_elements))
    
    # Process lifts in batches
    if lift_elements:
        total_lifts = len(lift_elements)
        for i in range(0, total_lifts, BATCH_SIZE):
            batch = lift_elements[i:i + BATCH_SIZE]
            log.info("Processing lift batch %d-%d of %d", i + 1, min(i + BATCH_SIZE, total_lifts), total_lifts)
            
            result = process_lifts(batch, progress, dry_run, instance_id)
            progress["lifts_synced"] = progress.get("lifts_synced", 0) + result["created"]
            progress["lifts_updated"] = progress.get("lifts_updated", 0) + result["updated"]
            
            log.info("  Batch result: %d created, %d updated, %d skipped",
                     result["created"], result["updated"], result["skipped"])
            
            # Save progress after each batch
            save_progress(instance_id, progress)
    
    # Final summary
    log.info("=" * 60)
    log.info("Worker %d completed!", instance_id)
    log.info("  Slopes: %d created, %d updated", progress["slopes_synced"], progress["slopes_updated"])
    log.info("  Lifts: %d created, %d updated", progress["lifts_synced"], progress["lifts_updated"])
    log.info("  Skipped records: %d", len(progress["skipped"]))
    log.info("  Progress saved to: %s", get_progress_file(instance_id))
    log.info("=" * 60)


# =============================================================================
# CLI Entry Point
# =============================================================================


def main():
    parser = argparse.ArgumentParser(
        description="Openslope OSM Data Collection Worker",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Run worker 1 for longitude range -180 to -144
  python collect_and_sync.py --instance-id 1 --lng-min -180 --lng-max -144

  # Dry run (preview without executing)
  python collect_and_sync.py --instance-id 1 --lng-min -180 --lng-max -144 --dry-run

  # Clear all progress files
  python collect_and_sync.py --clear
        """,
    )
    parser.add_argument(
        "--instance-id",
        type=int,
        required=True,
        help="Unique ID for this worker instance",
    )
    parser.add_argument(
        "--lng-min",
        type=float,
        required=True,
        help="Minimum longitude for this worker's range",
    )
    parser.add_argument(
        "--lng-max",
        type=float,
        required=True,
        help="Maximum longitude for this worker's range",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview API calls without executing them",
    )
    parser.add_argument(
        "--clear",
        action="store_true",
        help="Clear all progress files and exit",
    )
    
    args = parser.parse_args()
    
    if args.clear:
        clear_all_progress()
        log.info("All progress files cleared.")
        return
    
    # Validate longitude range
    if args.lng_min < -180 or args.lng_max > 180 or args.lng_min >= args.lng_max:
        log.error("Invalid longitude range: lng-min must be >= -180, lng-max must be <= 180, and lng-min < lng-max")
        sys.exit(1)
    
    run_worker(args.instance_id, args.lng_min, args.lng_max, args.dry_run)


if __name__ == "__main__":
    main()